### ISSUE TITLE
Binary File Access

### ISSUE THREAD

**Issue by lapplislazuli** [Tritlo/Endemic#20]
When I started to play with the docker-compose in #17, 
I first added the volume in read only like such: 

```yaml
version: '3.8'

services:
  ThreeFixes_Example:
    image: tritlo/endemic:latest
    volumes:
      - ./:/input:ro
    environment:
      REPAIR_TARGET: /input/ThreeFixes.hs
      LOG_LEVEL: "DEBUG"
    oom_kill_disable: true
```

That gives the following (interesting) Error 

```
Attaching to examples_ThreeFixes_Example_1
ThreeFixes_Example_1  | Up to date
ThreeFixes_Example_1  | endemic: /input/ThreeFixes.hi: openBinaryFile: permission denied (Read-only file system)
examples_ThreeFixes_Example_1 exited with code 1
```

Which is weird to me. 
Can we use a Read-Only-BinaryFile ?
